### ISSUE TITLE
How to chnage color scheme 

### ISSUE THREAD

**Issue by tsjazil** [grvxs/NVelox#9]
I want to change the color scheme from nord to my default terminal color scheme

**Comment by grvxs** [comment]
You need to find a neovim/vim plugin for the terminal color scheme you have.
I would suggest a [tree-sitter-compatible color scheme](https://github.com/rockerBOO/awesome-neovim#tree-sitter-supported-colorscheme).

If you are using the `~/.config/nvlx/init.lua` file for configuring NVelox you can refer to the following example.

For example, if you want the [material.nvim](https://github.com/marko-cerovac/material.nvim) colorscheme you'd add this in your `~/.config/nvlx/init.lua`:
```lua
nvlx.general = {
    colorscheme = "material",
}

nvlx.plugins = {
    "marko-cerovac/material.nvim",
}
```
Also, I would suggest not to use NVelox for now as it is still in development and has no documentation.

**Comment by tsjazil** [comment]
Oh Thanks :)
 BTW Its faster than my nvim
